// kaji ver 1.00 1957-mm-dd
var kajiDict=[
["ああ", "ああ", "ho!; [悲嘆] ve!, ho ve!; [疲] fu!"],
["ああけえど", "アーケード", "arkadaro, arkaĵaro."],
["ああす", "アース", "[ラジオなどの] terkonekto."],
["ああち", "アーチ", "[緑門] (verdfolia) arkaĵo."],
["ああめん", "アーメン", "amen; tiel estu."],
["ああゆうふうな", "ああいう(風な)", "tia."],
["あい", "愛", "amo; amsento; ampasio. ☆～する ami; ŝati."],
["あい", "藍", "indigo; bluo. ☆～色の indigoblua."],
["あいあい", "瞹々", "☆☆たる → 和気(わき)."],
["あいあいがさ", "相合傘", "☆～で行く iri sub unu[la sama] ombrelo."],
["あいいれない", "相容れない", "tute kontraŭa, kontraŭdira."],
["あいか", "哀歌", "elegio."],
["あいかぎ", "合鍵", "duplikata ŝlosilo."],
["あいかわらず", "相変らず", "kiel kutime, senŝanĝe."],
["あいがん", "哀願", "☆☆する humile peti, petegi."],
["あいきょう", "愛嬌", "☆☆のある ĉarma; aminda; afabla(愛想のよい)."],
["あいくち", "匕首", "ponardo."],
["あいくるしい", "愛くるしい", "aminda; ĉarma."],
["あいこ", "愛顧", "favoro; patroneco."],
["あいこ", "互角", "☆～の egal(fort)a. ☆～になる egaliĝi."],
["あいこう", "愛好", "☆～する ŝati, ami, esti amanto de. ☆音楽～者 muzikamanto."],
["あいこく", "愛国", "☆～心 patriotismo; [似非] ŝovinismo. ☆～者 patrioto, ŝovinisto."],
["あいことば", "合言葉", "signalvorto, ŝiboleto."],
["あいご", "愛護", "protektado."],
["あいさつ", "挨拶", "saluto; respondo(返事). ☆～する saluti."],
["あいし", "哀史", "malĝoja rakonto; tragika historio."],
["あいしゅう", "哀愁", "malĝojo; lament(ad)o."],
["あいしょう", "愛称", "karesa nomo."],
["あいじょう", "愛情", "amo; ampasio; korinklino."],
["あいじん", "愛人", "amat(in)o."],
["あいすくりいむ", "アイスクリーム", "glaciaĵo."],
["あいすらんど", "アイスランド", "Islando."],
["あいず", "合図", "signo; signalo(信号) ☆～をする fari signon."],
["あいせき", "愛惜", "☆☆する bedaŭri; malĝoji; lamenti."],
["あいそ", "哀訴(嘆願)", "☆☆する petegi; alpeti."],
["あいそう", "愛想", "☆～のよい afabla; gastama; societama. ☆～のない malafabla; malvarma. ☆～がつきる perdi amon[simpation] al iu."],
["あいそとおぷ", "アイソトープ", "[同位元素] izotopo."],
["あいぞう", "愛憎", "amo kaj malamo; partieco."],
["あいた", "明・空いた", "neokupita; vakanta; malfermita(開いた)."],
["あいた", "愛他", "☆～心[主義] altruismo."],
["あいたい", "相対", "☆☆で persone, senpere, inter si, reciproke; [合意で] interkonsentite, kun interkonsento."],
["あいたっ", "あ痛ッ！", "aj!"],
["あいだ", "間", "[空間] (inter)spaco; [時間] (inter)tempo; [距離] distanco; [中間] mezo. ☆～に [時間] dum; por; en la daŭro de; [物の] inter."],
["わりあて", "割当", "asigno. ☆～る asigni; dividi inter."],
["わりきれる", "割り切れる", "dividebla; konsolebla(気持が)."],
["わりこむ", "割り込む", "sin empuŝi en[inter]."],
["わりざん", "割算", "divido."],
["わりだす", "割り出す", "[算出] kalkuli; [推断] konjekti; dedukti; konkludi."],
["わりに", "割に", "kompare; relative."],
["わりびき", "割引", "rabato(値引); redukto(減額); diskonto(手形など)."],
["わりふる", "割り振る", "asigni."],
["わりまえ", "割前", "ies parto, kotizo."],
["わりまし", "割増し", "ekstra pago, krompago."],
["わりもどし", "割戻し", "rabato; repago."],
["わる", "割る", "①[分割] dividi; tranĉi(切って); ②[分離] apartigi; ③[裂く] spliti; (dis)fendi; ④[こわす] rompi."],
["わるい", "悪い", "malbona; [不正] maljusta; [悪意] malica; [不吉] malfeliĉa; [病気] malsana; [腐敗] putra; [有害] malutila."],
["わるがしこい", "悪賢い", "ruza."],
["わるぎ", "悪気", "malbona intenco; malbona volo; malico."],
["わるくち", "悪口", "☆☆を言う klaĉi; insulti; kalumnii."],
["わるさ", "悪戯", "→悪戯(いたずら)."],
["わるそう", "ワルソー・ワルシャワ", "Varsovio."],
["わるつ", "ワルツ", "[舞踏の] valso."],
["わるびれる", "悪びれる", "timi(臆する); heziti(ためらう)."],
["わるもの", "悪者", "malbonulo; kanajlo; fripono."],
["われ", "我", "[私] mi; [自身] si mem; [自我] memo, egoo. ☆～を忘れる forgesi sin mem. ☆～に返る rekonsciiĝi."],
["われがち", "我勝ち", "ĉiu por si mem; konkure."],
["われしらず", "我知らず", "senkonscie; senintence; instinkte."],
["われめ", "割れ目", "fendo."],
["われる", "割れる", "[破壊] rompiĝi; dispeciĝi, diskraki(こなごなに); [裂ける] (dis)krevi; splitiĝi; [亀裂] fendiĝi; [分裂] skismi. ☆～ような拍手 tondra aplaŭd(ad)o."],
["われわれ", "我々", "ni. ☆～の nia."],
["わん", "椀", "(ligna) bovlo."],
["わん", "湾", "golfo."],
["わんきょく", "彎曲", "kurbeco; kurbiĝo."],
["わんしょう", "腕章", "brakbendo, brakstrio."],
["わんぱく", "腕白", "☆☆な petol(em)a."],
["わんりょく", "腕力", "muskola forto; perforto(暴力). ☆～沙汰になる veni al pugnobatoj."]
];

